version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
    commands:
      - echo Installing dependencies...
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 223263957253.dkr.ecr.ap-south-1.amazonaws.com
      - echo Logged in successfully.
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t php-app .
      - docker tag php-app:latest 223263957253.dkr.ecr.ap-south-1.amazonaws.com/php-app:latest
  post_build:
    commands:
      - echo Pushing the Docker image...
      - docker push 223263957253.dkr.ecr.ap-south-1.amazonaws.com/php-app:latest
      - echo Build completed on `date`
artifacts:
  files: none
