version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
    commands:
      - echo Installing dependencies...
      - apt-get update -y
      - apt-get install -y amazon-ecr-credential-helper
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 223263957253.dkr.ecr.ap-south-1.amazonaws.com
      - REPOSITORY_URI=223263957253.dkr.ecr.ap-south-1.amazonaws.com/php-app
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t php-app -f dockerfile .
      - docker tag php-app:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Pushing the Docker image to ECR...
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Build completed on `date`
artifacts:
  files: none

